name: Build APK and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: apk-release
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          cache: true

      - name: Flutter Version
        run: flutter --version

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Verify APK Exists
        id: apk
        run: |
          APK="build/app/outputs/flutter-apk/app-release.apk"

          if [ ! -f "$APK" ]; then
            echo "APK was not generated."
            exit 1
          fi

          echo "apk=$APK" >> "$GITHUB_OUTPUT"

      - name: Generate Release Tag
        id: tag
        run: |
          TAG="v$(date +'%Y.%m.%d-%H%M%S')"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"


      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            "${{ steps.tag.outputs.tag }}" \
            "${{ steps.apk.outputs.apk }}" \
            --title "${{ steps.tag.outputs.tag }}" \
            --notes "Automated APK build"
